apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-user-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Ti
  volumeName: nextcloud-user-data
  storageClassName: ""
