apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-user-data
  labels:
    app.kubernetes.io/instance: nextcloud
spec:
  capacity:
    storage: 3Ti
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  hostPath:
    path: /mnt/storage/nextcloud-k3s
    type: Directory
  claimRef:
    name: nextcloud-user-data
    namespace: nextcloud
