apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pump-price-secrets
  namespace: pump-price
spec:
  encryptedData:
    ELASTICSEARCH_PASSWORD: REPLACE_WITH_SEALED_VALUE
    INGESTION_API_KEY: REPLACE_WITH_SEALED_VALUE
  template:
    metadata:
      name: pump-price-secrets
      namespace: pump-price
    type: Opaque
