---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: otel-es-credentials
  namespace: observability
spec:
  encryptedData:
    ES_PASSWORD: AgDGFHGUL4kasq/4spWoadJW2rh/YRaz78u5zj37lIXu7jeR93OZJHQEfOywdVxj76RJRVNWL/URGa2hJftROUnh05hVj5UiUJvvFUCtnymkyS+rfSpaFE1A8YEbSqMzylV5m7A9oV6sGiPZu7JjZY+16MUIu9fr+/b5aWXol+nidOigSCvdsqqD7WIh6sdSfyQC9pQNF09ZKiGBqTQldgV1skfL5qBktwc4Jtv/JDJTn2p3HXBT7bpw+GEjFO7gj/6+2fzKtPgFsehOhlAfP3bLxT/xqQYc0ieg4V0cylXaJnwM9ag5CaFXKkwk6q90Ye4+GH76HcTZaJWXEg8dEVp+T9gAGQJLczucODOc5fxFsdcWF6mYcdLcB5muuKE5TeMXDbIGr8UrLSrzNxp0JgSABlk1ETNsrlkZFta0hDpIE5luO97c+hVlL73rkVIDI91sOuZOxpZzXK7jJzELTbYMSAc/cvvb5VPEzVZG7Vt8E03e/rO5MBn7URZbTrTooDxAylTZSSndFZtBK9zuPhhr39CH9IDdJftPTFIYWOvqeTcG91ViApgE2u8Gq3c/zYwN3Jbs2xEDWmgaTjbuATDux0APQvOdlQugc0hQXyBpkw9SnJIbhy3wVWZ5BTtZiOhb+qLCzwBiH6sYtpn71X3u4bUpr3s89X1cVOizofAaVRBB93PE0cJC2wDXcqGpcmB6E5MOn7BWEE9VpKHiZGNuQAOxyhbg8eI=
  template:
    metadata:
      creationTimestamp: null
      name: otel-es-credentials
      namespace: observability
