opentelemetry-collector:
  mode: daemonset

  image:
    repository: "otel/opentelemetry-collector-contrib"

  presets:
    logsCollection:
      enabled: true
    hostMetrics:
      enabled: true
    kubeletMetrics:
      enabled: true
    kubernetesAttributes:
      enabled: true

  extraEnvsFrom:
    - secretRef:
        name: otel-es-credentials

  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
        timeout: 1s
        send_batch_size: 512
        send_batch_max_size: 1024
      memory_limiter:
        check_interval: 1s
        limit_mib: 400
        spike_limit_mib: 100

    exporters:
      elasticsearch:
        endpoints:
          - https://elasticsearch-es-http.observability.svc:9200
        tls:
          insecure_skip_verify: true
        user: elastic
        password: ${env:ES_PASSWORD}
        mapping:
          mode: ecs
        num_workers: 4
        flush:
          bytes: 5242880
      debug:
        verbosity: basic

    extensions:
      health_check: {}

    service:
      extensions:
        - health_check
      pipelines:
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [elasticsearch, debug]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [elasticsearch, debug]
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [elasticsearch, debug]

  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 512Mi
